# Generated by Django 4.1.5 on 2023-02-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_executive',
        ),
    ]
