# Generated by Django 4.1.5 on 2023-02-12 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_event_event_date_alter_event_token_dist_end_and_more'),
        ('users', '0002_rename_is_manager_user_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokens.event', verbose_name='Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
