# Generated by Django 4.1.5 on 2023-02-11 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Event')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('event_date', models.DateField()),
                ('token_usage', models.IntegerField(default=0)),
                ('distribution_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distribution')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_serial', models.AutoField(primary_key=True, serialize=False, verbose_name='Serial')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokens.event', verbose_name='Event')),
            ],
            options={
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tokens.tag'),
        ),
    ]
