# Generated by Django 4.1.5 on 2023-02-02 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_serial', models.IntegerField(default=datetime.datetime.now, verbose_name='Serial')),
            ],
            options={
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
