# Generated by Django 4.1.5 on 2023-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_alter_event_created_date_alter_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='token_dist_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='token_dist_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
