# Generated by Django 4.1.5 on 2023-02-02 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_token_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_serial',
            field=models.IntegerField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Serial'),
        ),
    ]
