# Generated by Django 4.1.5 on 2023-02-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_event_event_date_alter_event_token_dist_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Activated'),
        ),
        migrations.AddField(
            model_name='token',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Printed'),
        ),
        migrations.AddField(
            model_name='token',
            name='student_id',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Student Id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='token_usage',
            field=models.IntegerField(default=0, verbose_name='Token Usage Limit'),
        ),
    ]
