# Generated by Django 4.1.5 on 2023-02-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_token_token_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_serial',
            field=models.IntegerField(blank=True, default=20230202219150, null=True, verbose_name='Serial'),
        ),
    ]
