# Generated by Django 4.1.5 on 2023-02-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_token_is_activated_token_is_printed_token_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='usage',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Token Usage'),
        ),
    ]
