# Generated by Django 4.1.5 on 2023-02-17 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_token_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=8, null=True, verbose_name='Student Id')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokens.event', verbose_name='Event')),
            ],
            options={
                'verbose_name_plural': 'Student List',
            },
        ),
    ]
