# Generated by Django 4.1.5 on 2023-02-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_alter_token_token_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_serial',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Serial'),
        ),
    ]
