# Generated by Django 4.1.5 on 2023-02-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0007_alter_token_token_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AlterField(
            model_name='token',
            name='token_serial',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Serial'),
        ),
    ]
