# Generated by Django 4.1.5 on 2023-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0008_alter_studentlist_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='claimed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Token Claimed'),
        ),
    ]
