# Generated by Django 4.1.5 on 2023-02-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0008_remove_token_id_alter_token_token_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_event',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event'),
        ),
    ]
