# Generated by Django 4.1.5 on 2023-02-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0011_remove_event_tags_token_entry_flag_token_food_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='usage',
        ),
    ]
